# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# 资源大集合
# https://zhuanlan.zhihu.com/p/435173554
target 'swift_master' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift_master
  pod 'Log4swift', '1.2.0'
  pod 'Moya', '~> 15.0.0'
  pod 'RxSwift', '~> 6.2.0'
  pod 'MonkeyKing', '~> 2.2.1'
  pod 'SwiftyJSON', '~> 5.0.1'
  pod 'ObjectMapper', '~> 4.2.0'
# 无需扩展任何内置对象就为Swift语言提供有效的函数式编程辅助方法,类似于Lo-Dash或JavaScript中的Underscore
  pod 'Dollar', '~> 9.0.0'
  pod 'SwiftString', '~> 0.5'

  target 'swift_masterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift_masterUITests' do
    # Pods for testing
  end

end
